### ISSUE TITLE
No more CommonJS support

### ISSUE THREAD

**Issue by darkmavis1980** [middyjs/middy#837] opened 2022-05-16 14:46 UTC
**Describe the bug**
I understand that version 3 of Middy now supports ESM, but now my existing serverless functions cannot longer work with that version as they use CommonJS, and to convert them to ESM requires the conversion of my code and a few other external dependencies.
So I presume there's no alternative from version 3 onwards, is it either ESM or nothing?

**Comment by willfarrell** [comment] 2022-05-16 15:36
v3 does contain a CommonJS transpiled version within the package (why they're larger this version). It should automatically be connected when you use `require(...)`.

This is how it's configured:
```
"exports": {
    ".": {
      "import": "./index.js",
      "require": "./index.cjs",
      "types": "./index.d.ts"
    }
  }
```
I did test it manually without issue.

Is your npm up to date?

**Comment by darkmavis1980** [comment] 2022-05-16 15:55
Hi, I do, I'm actually using Node 16 since AWS now supports that version, but I get various errors if I upgrade to @middy/core v3, the very moment I upgrade from v2 to v3 I get the following error when running the functions:
```
offline: one of the module nesting myFunction for handler myFunction is undefined or not exported
```
And here how I do export the handler:

```javascript
const middy = require('@middy/core');
const jsonBodyParser = require('@middy/http-json-body-parser');
const httpHeaderNormalizer = require('@middy/http-header-normalizer');
const httpUrlEncodeBodyParser = require('@middy/http-urlencode-body-parser');
const cors = require('@middy/http-cors');

const myFunction = async (event) => {
// my code
}

const myFunctionHandler = middy(myFunction);

myFunctionHandler
  .use(cors(corsOptions))
  .use(jsonBodyParser())
  .use(httpUrlEncodeBodyParser())
  .use(httpHeaderNormalizer());
```

**Comment by willfarrell** [comment] 2022-05-16 16:07
I see the issue. The the transpiler is exporting using `var _default=middy;exports.default=_default` instead of `module.exports=middy`. I'm not sure why they do this, it also effects `ajv` and a few others I use, super annoying.

I should be able to add in hack to build step to do a find and replace `exports.default` to allow it to be used as expect. I'll try and get to it this week. Thanks for reporting.

**Comment by willfarrell** [comment] 2022-05-17 02:41
v3.0.3 now released, hopefully it resolves this issue.

**Comment by darkmavis1980** [comment] 2022-05-17 08:30
Just tested and everything is working perfectly!
Thanks for fixing it so quickly and for your work on this library!

**Comment by darkmavis1980** [comment] 2022-05-17 10:34
Uhm, actually if I run the serverless endpoints they run fine, but my integration tests fail now, I'll try to do some investigations on my side, but I noticed that again, going back to v2 it fixes 🤔

**Comment by willfarrell** [comment] 2022-05-17 15:02
Re the middy object, that is expected. `__middlewares` and `applyMiddleware` were deprecated. The middlewares are there, just not accessible for tampering anymore.

Your jest error makes me think your test input is missing the headers object which would be expected to be there in a http event.

**Comment by darkmavis1980** [comment] 2022-05-17 15:07
Uhm probably yeah, in that case, it's probably my code, I'll close this issue

**Comment by willfarrell** [comment] 2022-05-17 15:08
Please report back, just to make sure.

**Comment by cortexcompiler** [comment] 2022-05-17 15:18
If I upgrade to `@middy/core@3.0.3` I begin seeing an ECMAScript module in my unit tests that were working.  If I downgrade the tests succeed without any coding change.  I believe this is related.  The specific error is `SyntaxError: Cannot use import statement outside a module`, related to the `export default middy` export. Below are the error details:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    <project-path>/node_modules/@middy/core/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import{EventEmitter}from"events";const defaultLambdaHandler=()=>{};const defaultPlugin={timeoutEarlyInMillis:5,timeoutEarlyResponse:()=>{throw new Error("Timeout")}};const middy=(lambdaHandler=defaultLambdaHandler,plugin={})=>{if(typeof lambdaHandler!=="function"){plugin=lambdaHandler;lambdaHandler=defaultLambdaHandler}plugin={...defaultPlugin,...plugin};plugin.timeoutEarly=plugin.timeoutEarlyInMillis>0;plugin.beforePrefetch?.();const beforeMiddlewares=[];const afterMiddlewares=[];const onErrorMiddlewares=[];const middy1=(event={},context={})=>{plugin.requestStart?.();const request={event,context,response:undefined,error:undefined,internal:plugin.internal??{}};return runRequest(request,[...beforeMiddlewares],lambdaHandler,[...afterMiddlewares],[...onErrorMiddlewares],plugin)};middy1.use=middlewares=>{if(!Array.isArray(middlewares)){middlewares=[middlewares]}for(const middleware of middlewares){const{before,after,onError}=middleware;if(!before&&!after&&!onError){throw new Error('Middleware must be an object containing at least one key among "before", "after", "onError"')}if(before)middy1.before(before);if(after)middy1.after(after);if(onError)middy1.onError(onError)}return middy1};middy1.before=beforeMiddleware=>{beforeMiddlewares.push(beforeMiddleware);return middy1};middy1.after=afterMiddleware=>{afterMiddlewares.unshift(afterMiddleware);return middy1};middy1.onError=onErrorMiddleware=>{onErrorMiddlewares.unshift(onErrorMiddleware);return middy1};middy1.handler=replaceLambdaHandler=>{lambdaHandler=replaceLambdaHandler;return middy1};return middy1};const runRequest=async(request,beforeMiddlewares,lambdaHandler,afterMiddlewares,onErrorMiddlewares,plugin)=>{const timeoutEarly=plugin.timeoutEarly&&request.context.getRemainingTimeInMillis;try{await runMiddlewares(request,beforeMiddlewares,plugin);if(request.response===undefined){plugin.beforeHandler?.();const handlerAbort=new AbortController;let timeoutAbort;if(timeoutEarly)timeoutAbort=new AbortController;request.response=await Promise.race([lambdaHandler(request.event,request.context,{signal:handlerAbort.signal}),timeoutEarly?setTimeoutPromise(request.context.getRemainingTimeInMillis()-plugin.timeoutEarlyInMillis,{signal:timeoutAbort.signal}).then(()=>{handlerAbort.abort();return plugin.timeoutEarlyResponse()}):Promise.race([])]);if(timeoutEarly)timeoutAbort.abort();plugin.afterHandler?.();await runMiddlewares(request,afterMiddlewares,plugin)}}catch(e){request.response=undefined;request.error=e;try{await runMiddlewares(request,onErrorMiddlewares,plugin)}catch(e){e.originalError=request.error;request.error=e;throw request.error}if(request.response===undefined)throw request.error}finally{await plugin.requestEnd?.(request)}return request.response};const runMiddlewares=async(request,middlewares,plugin)=>{for(const nextMiddleware of middlewares){plugin.beforeMiddleware?.(nextMiddleware.name);const res=await nextMiddleware(request);plugin.afterMiddleware?.(nextMiddleware.name);if(res!==undefined){request.response=res;return}}};const polyfillAbortController=()=>{if(process.version<"v15.0.0"){let _toStringTag;let _toStringTag1=Symbol.toStringTag;class AbortSignal{toString(){return"[object AbortSignal]"}get[_toStringTag1](){return"AbortSignal"}removeEventListener(name,handler){this.eventEmitter.removeListener(name,handler)}addEventListener(name,handler){this.eventEmitter.on(name,handler)}dispatchEvent(type){const event={type,target:this};const handlerName=`on${type}`;if(typeof this[handlerName]==="function")this[handlerName](event);this.eventEmitter.emit(type,event)}constructor(){this.eventEmitter=new EventEmitter;this.onabort=null;this.aborted=false}}return _toStringTag=Symbol.toStringTag,class AbortController{abort(){if(this.signal.aborted)return;this.signal.aborted=true;this.signal.dispatchEvent("abort")}toString(){return"[object AbortController]"}get[_toStringTag](){return"AbortController"}constructor(){this.signal=new AbortSignal}}}else{return AbortController}};global.AbortController=polyfillAbortController();const polyfillSetTimeoutPromise=()=>{return(ms,{signal})=>{if(signal.aborted){return Promise.reject(new Error("Aborted","AbortError"))}return new Promise((resolve,reject)=>{const abortHandler=()=>{clearTimeout(timeout);reject(new Error("Aborted","AbortError"))};const timeout=setTimeout(()=>{resolve();signal.removeEventListener("abort",abortHandler)},ms);signal.addEventListener("abort",abortHandler)})}};const setTimeoutPromise=polyfillSetTimeoutPromise();export default middy
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import middy from '@middy/core';
```

This happens with `ts-jest` or `esbuild-jest` and with various configurations of the compiler `target` (e.g. `es2017`, `es2020`) and `module` (e.g. `es2015`, `commonjs`) versions.

**Comment by cortexcompiler** [comment] 2022-05-17 15:29
> 

I am using this with AWS SAM.  However, the issue is really TypeScript and jest related as far as I can tell.

**Comment by willfarrell** [comment] 2022-05-17 16:16
We actually stopped using Babel and Jest within Middy partly because of errors like this.

The npm packages have both CommonJS and ESM within them and are pre-compiled to `target: es2020` using `swc`.

The TypeScript transpiler isn't handling nested dependencies as expected it seems. This usually means a config error of some kind. In this case `events` is part of nodejs. Does there need to be a flag in the config to let it know how to handle this properly? Also the mixing of package.json `type` value being commonjs/module, the test written in cjs/esm, and the compiled code being in cjs/esm can cause all sorts of issues like this.

Possible workaround: `import middy from '@middy/core/index.cjs'` this is equivalent to what is in v2.

Note: AWS Lambda does support running ESM on nodejs14.x, if you don't use lambda layers or the `aws-sdk` in the runtime itself.

**Comment by lucadv** [comment] 2022-05-25 07:46
> I still a related issue if I upgrade to `@middy/core@3.0.3` I begin seeing an ECMAScript module related error in my unit tests that previously worked. If I downgrade the tests succeed without any coding change. I believe this is related. The specific error is `SyntaxError: Cannot use import statement outside a module`, related to the `export default middy` export. Below are the error details:
> 
> ```
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>     Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>     By default "node_modules" folder is ignored by transformers.
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>      • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/configuration
>     For information about custom transformations, see:
>     https://jestjs.io/docs/code-transformation
> 
>     Details:
> 
>     <project-path>/node_modules/@middy/core/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import{EventEmitter}from"events";const defaultLambdaHandler=()=>{};const defaultPlugin={timeoutEarlyInMillis:5,timeoutEarlyResponse:()=>{throw new Error("Timeout")}};const middy=(lambdaHandler=defaultLambdaHandler,plugin={})=>{if(typeof lambdaHandler!=="function"){plugin=lambdaHandler;lambdaHandler=defaultLambdaHandler}plugin={...defaultPlugin,...plugin};plugin.timeoutEarly=plugin.timeoutEarlyInMillis>0;plugin.beforePrefetch?.();const beforeMiddlewares=[];const afterMiddlewares=[];const onErrorMiddlewares=[];const middy1=(event={},context={})=>{plugin.requestStart?.();const request={event,context,response:undefined,error:undefined,internal:plugin.internal??{}};return runRequest(request,[...beforeMiddlewares],lambdaHandler,[...afterMiddlewares],[...onErrorMiddlewares],plugin)};middy1.use=middlewares=>{if(!Array.isArray(middlewares)){middlewares=[middlewares]}for(const middleware of middlewares){const{before,after,onError}=middleware;if(!before&&!after&&!onError){throw new Error('Middleware must be an object containing at least one key among "before", "after", "onError"')}if(before)middy1.before(before);if(after)middy1.after(after);if(onError)middy1.onError(onError)}return middy1};middy1.before=beforeMiddleware=>{beforeMiddlewares.push(beforeMiddleware);return middy1};middy1.after=afterMiddleware=>{afterMiddlewares.unshift(afterMiddleware);return middy1};middy1.onError=onErrorMiddleware=>{onErrorMiddlewares.unshift(onErrorMiddleware);return middy1};middy1.handler=replaceLambdaHandler=>{lambdaHandler=replaceLambdaHandler;return middy1};return middy1};const runRequest=async(request,beforeMiddlewares,lambdaHandler,afterMiddlewares,onErrorMiddlewares,plugin)=>{const timeoutEarly=plugin.timeoutEarly&&request.context.getRemainingTimeInMillis;try{await runMiddlewares(request,beforeMiddlewares,plugin);if(request.response===undefined){plugin.beforeHandler?.();const handlerAbort=new AbortController;let timeoutAbort;if(timeoutEarly)timeoutAbort=new AbortController;request.response=await Promise.race([lambdaHandler(request.event,request.context,{signal:handlerAbort.signal}),timeoutEarly?setTimeoutPromise(request.context.getRemainingTimeInMillis()-plugin.timeoutEarlyInMillis,{signal:timeoutAbort.signal}).then(()=>{handlerAbort.abort();return plugin.timeoutEarlyResponse()}):Promise.race([])]);if(timeoutEarly)timeoutAbort.abort();plugin.afterHandler?.();await runMiddlewares(request,afterMiddlewares,plugin)}}catch(e){request.response=undefined;request.error=e;try{await runMiddlewares(request,onErrorMiddlewares,plugin)}catch(e){e.originalError=request.error;request.error=e;throw request.error}if(request.response===undefined)throw request.error}finally{await plugin.requestEnd?.(request)}return request.response};const runMiddlewares=async(request,middlewares,plugin)=>{for(const nextMiddleware of middlewares){plugin.beforeMiddleware?.(nextMiddleware.name);const res=await nextMiddleware(request);plugin.afterMiddleware?.(nextMiddleware.name);if(res!==undefined){request.response=res;return}}};const polyfillAbortController=()=>{if(process.version<"v15.0.0"){let _toStringTag;let _toStringTag1=Symbol.toStringTag;class AbortSignal{toString(){return"[object AbortSignal]"}get[_toStringTag1](){return"AbortSignal"}removeEventListener(name,handler){this.eventEmitter.removeListener(name,handler)}addEventListener(name,handler){this.eventEmitter.on(name,handler)}dispatchEvent(type){const event={type,target:this};const handlerName=`on${type}`;if(typeof this[handlerName]==="function")this[handlerName](event);this.eventEmitter.emit(type,event)}constructor(){this.eventEmitter=new EventEmitter;this.onabort=null;this.aborted=false}}return _toStringTag=Symbol.toStringTag,class AbortController{abort(){if(this.signal.aborted)return;this.signal.aborted=true;this.signal.dispatchEvent("abort")}toString(){return"[object AbortController]"}get[_toStringTag](){return"AbortController"}constructor(){this.signal=new AbortSignal}}}else{return AbortController}};global.AbortController=polyfillAbortController();const polyfillSetTimeoutPromise=()=>{return(ms,{signal})=>{if(signal.aborted){return Promise.reject(new Error("Aborted","AbortError"))}return new Promise((resolve,reject)=>{const abortHandler=()=>{clearTimeout(timeout);reject(new Error("Aborted","AbortError"))};const timeout=setTimeout(()=>{resolve();signal.removeEventListener("abort",abortHandler)},ms);signal.addEventListener("abort",abortHandler)})}};const setTimeoutPromise=polyfillSetTimeoutPromise();export default middy
>                                                                                       ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>     > 1 | import middy from '@middy/core';
> ```
> 
> This happens with `ts-jest` or `esbuild-jest` and with various configurations of the compiler `target` (e.g. `es2017`, `es2020`) and `module` (e.g. `es2015`, `commonjs`) versions.

I have had this exact same issue when I inadvertently upgraded all middy packages to v3 and downgrading to v2 solved the issue.

**Comment by willfarrell** [comment] 2022-06-04 21:24
Closing because the original cjs issue is resolved. We can continue the esm issue in https://github.com/middyjs/middy/issues/843

**Closed by willfarrell** 2022-06-04 21:24 UTC
Labels: bug

**Comment by willfarrell** [comment] 2022-06-10 18:25
I've updated https://middy.js.org/docs/best-practices/bundling/#webpack after some more testing, hope this helps.
