### ISSUE TITLE
Question about modifying `handler.context` in middleware

### ISSUE THREAD

**Issue by stephanschubert** [middyjs/middy#223] opened 2018-08-18 08:46 UTC
I've noticed that you have to use `Object.assign` to make it work:

```
    const env = { foo: "bar" };
    Object.assign(handler.context, { env });
```

But this doesn't:

```
    const env = { foo: "bar" };
    handler.context = {
      ...handler.context,
      env,
    };
```

Is this expected?

**Comment by lmammino** [comment] 2018-08-18 14:36
Hello @jazen, sorry if i answer to a question with another one... what are you trying to achieve and what kind of error do you get?

**Comment by jazen** [comment] 2018-09-11 16:27
@lmammino Sorry for the late answer - Usually I use the spread operator `...` instead of `Object.assign` and wondered why that won't work here.

**Comment by lmammino** [comment] 2018-09-12 20:06
Which runtime are you using? Are you sure you are not running your lambda on Node 6.x? In Node 8.10 I believe the object spread syntax should work.

**Comment by jazen** [comment] 2018-09-13 05:42
I'm sorry for wasting your time but I can't reproduce the issue anymore. I'm pretty sure I hadn't been using node 6.x because I'm using `nvm` for months now:

```
nvm ls
         v7.9.0
         v8.1.4
        v9.10.1
->      v10.5.0
default -> 8 (-> v8.1.4)
```

Somehow it works now. Maybe some weird behavior with long-running shells and nvm? Who knows... Sorry again. Closing it.

**Comment by stephanschubert** [comment] 2019-04-28 18:30
@lmammino I have to re-open the issue because I ran into again and realized that [every handler gets the original `context` object passed as argument](https://github.com/middyjs/middy/blob/1.0.0-alpha/packages/core/index.js#L189) and not `instance.context`.

So `Object.assign` works because it in-place but re-assigning `handler.context = ...` has no effect therefore.

Is this behaviour intended?

**Comment by willfarrell** [comment] 2020-12-29 01:53
Going to close for now. If you're still experiencing this on node v12 please reopen.

**Closed by willfarrell** 2020-12-29 01:53 UTC

**Comment by calvin-summer** [comment] 2021-12-07 03:02
Hi @willfarrell 
I'm experiencing this same issue on node 14. I'm interested to know if this would be considered a bug or expected behavior? Re: Op's initial example

**Comment by willfarrell** [comment] 2021-12-07 04:28
In middy v2, both should be allowed. See the unit test for the core package

https://github.com/middyjs/middy/blob/main/packages/core/__tests__/index.js#L186-L219
