### ISSUE TITLE
Cannot extend Context type

### ISSUE THREAD

**Issue by moltar** [middyjs/middy#540] opened 2020-06-29 01:47 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create an interface that extends `Context` type
2. Create a middleware with the extended `Context` 
3. Supply the middleware to `use` method

What happens?
-------------

`use` method throws an TypeScript error.

What were you expecting to happen?
----------------------------------

Extended type to be accepted.

Any logs, error output, etc?
----------------------------

```
Argument of type 'MiddlewareObject<SQSEvent, unknown, Ctx>' is not assignable to parameter of type 'MiddlewareObject<SQSEvent, unknown, Context> | MiddlewareObject<SQSEvent, unknown, Context>[]'.
  Type 'MiddlewareObject<SQSEvent, unknown, Ctx>' is not assignable to type 'MiddlewareObject<SQSEvent, unknown, Context>'.
    Types of property 'before' are incompatible.
      Type 'MiddlewareFunction<SQSEvent, unknown, Ctx> | undefined' is not assignable to type 'MiddlewareFunction<SQSEvent, unknown, Context> | undefined'.
        Type 'MiddlewareFunction<SQSEvent, unknown, Ctx>' is not assignable to type 'MiddlewareFunction<SQSEvent, unknown, Context>'.
          Types of parameters 'handler' and 'handler' are incompatible.
            Type 'HandlerLambda<SQSEvent, unknown, Context>' is not assignable to type 'HandlerLambda<SQSEvent, unknown, Ctx>'.
              Types of property 'context' are incompatible.
                Type 'Context' is not assignable to type 'Ctx'.ts(2345)
```

Any other comments?
-------------------

```ts
import { Context, SQSEvent } from 'aws-lambda'

interface Ctx extends Context {
  foo: string
}

const mw: middy.MiddlewareObject<Event, Res, Ctx> = {
  before: ({ context }) => {
    return Promise.resolve()
  },
}

// ...

// errors here
handler.use(mw)
```

What versions of software are you using?
----------------------------------------
**Node.js Version:** v12.16.0

**Middy Version:** 1.0.0

**AWS SDK Version:** 2.697.0

**Comment by moltar** [comment] 2020-06-29 01:49
I see maybe #275 is relevant here.

Making the prop optional actually makes it work.

**Comment by willfarrell** [comment] 2020-07-24 07:58
Is there something we can add to the ts code or the docs to help others? Would you be able to make a quick PR?

**Comment by russell-dot-js** [comment] 2020-08-27 23:17
Related: #556

**Comment by willfarrell** [comment] 2020-08-29 17:47
#556 has been merge and will be released soon (v1.3.0), please post if it's still an issue

**Comment by moltar** [comment] 2020-08-29 22:17
I'm not seeing any TypeScript definition changes in the PR. I don't think this PR would solve the original issue.

**Comment by StErMi** [comment] 2020-11-25 18:12
I think the issue is still here with version `1.4.0`

**Comment by baileytincher** [comment] 2020-12-30 01:30
This appears to be more of a user error than an issue with the library. You typed your middleware with a custom context that has a required attribute but then did not type your handler with the same custom context. I think that the type error here is the proper behavior and will avoid potential bugs/confusion for other users.

**Comment by willfarrell** [comment] 2020-12-30 19:50
I'm going to close for now. All ts definitions will be redo in middy v2. I will need help, as I don't know TS, please post on https://github.com/middyjs/middy/pull/587 if you can help when it's ready.

**Closed by willfarrell** 2020-12-30 19:50 UTC
Labels: type-systems
