### ISSUE TITLE
Regression: Response serializer no longer replaces response

### ISSUE THREAD

**Issue by roni-frantchi** [middyjs/middy#657] opened 2021-04-19 12:52 UTC
What are the steps to reproduce this issue?
-------------------------------------------
Create a serializer that returns an object.  

What happens?
-------------
The serializer returned object is set on the body.  

What were you expecting to happen?
----------------------------------
The returned object should replace the entire response object as [the documentation states](https://github.com/middyjs/middy/tree/main/packages/http-response-serializer#serializer-functions):  

> _"...If an object is returned, the entire response object is replaced. This is useful if you want to manipulate headers or add additional attributes in the Lambda response."_

 (and as it was in v1) 

Any other comments?
-------------------
Seems to me like the behavior had changed since [this change](https://github.com/middyjs/middy/commit/610c64e47f85e210d942524d4665c264825d94ed#diff-d2f4c1e6809f1ffc51d2b64a7c53730ddaa4d2cef8193db00cf9c76f4711a8d0L42)

I think the only reason the [pre-existing unit test](https://github.com/middyjs/middy/blob/main/packages/http-response-serializer/__tests__/index.js#L208) did not break was because the response object itself [was mutated](https://github.com/middyjs/middy/blob/main/packages/http-response-serializer/__tests__/index.js#L217).  

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14

**Middy Version:** 2.0.1

**Comment by willfarrell** [comment] 2021-04-19 15:29
How did you get 7 `+1` in 3h? Anyways, I should be able to take a look later today.

**Comment by willfarrell** [comment] 2021-04-19 21:16
I see the regression,

v1.x
```js
const result = s.serializer(handler.response)

    if (typeof result === 'object') {
      // replace response object if result is object
      handler.response = result
    } else {
      // otherwise only replace the body attribute
      handler.response.body = result
    }
```

v2.x
```js
request.response.body = s.serializer(request.response)
```

I do recall simplifying because any object doesn't mean it will be an acceptable response for http. How about this:

```js
    const result = s.serializer(handler.response)
    if (result?.body) {
      handler.response = result
    } else {
      // otherwise only replace the body attribute
      handler.response.body = result
    }
```

This should give you the flexibility you need while ensuring the correct response structure is maintained. Let me know if this works for you, I can add it in.

**Comment by roni-frantchi** [comment] 2021-04-20 10:38
@willfarrell that will work just as well I think, thank you.

**Comment by willfarrell** [comment] 2021-04-20 16:42
Will be in the next release. v2.1.0

**Closed** 2021-04-20 16:42 UTC

**Comment by RaeesBhatti** [comment] 2021-04-20 20:45
It would be great if this is released soon because it's currently breaking our flow. Thanks!

**Comment by willfarrell** [comment] 2021-04-20 21:58
It will likely be released this week. I'm just waiting on feedback for a new middleware.

**Comment by roni-frantchi** [comment] 2021-04-26 09:40
Thanks for the prompt release @willfarrell.  
Seems like there's one case I've missed which I think what you've suggested won't be good enough.  
I'm thinking of cases where the response would be something like `204` - in that case I'd expect the response not to have a `body`.  
Maybe we'd do better to be looking for `statusCode` rather than `body`?...

**Comment by roni-frantchi** [comment] 2021-04-26 10:13
Or perhaps - check if `hasOwnProperty('body')` so that one may `body: undefined`

**Comment by roni-frantchi** [comment] 2021-04-26 10:50
OK so it's worse than that @willfarrell - if one has `false` as their `body`, the behavior is also not what you would expect.  

I think we would have to check for `hasOwnProperty('body')`

**Comment by willfarrell** [comment] 2021-04-26 13:20
v2.1.1 is on it's way
