### ISSUE TITLE
headers[headerName].trim is not a function"

### ISSUE THREAD

**Issue by carrickkv2** [middyjs/middy#1097] opened 2023-09-04 17:20 UTC
Describe the bug
When using the middy s3 middleware on AWS, I always get the error below.

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: headers[headerName].trim is not a function",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "headers[headerName].trim is not a function",
        "$metadata": {
            "attempts": 1,
            "totalRetryDelay": 0
        },
        "stack": [
            "TypeError: headers[headerName].trim is not a function",
            "    at getCanonicalHeaders (/var/task/src/handlers/event/sendSMS.js:3485:62)",
            "    at SignatureV4.signRequest (/var/task/src/handlers/event/sendSMS.js:3838:80)",
            "    at async /var/task/src/handlers/event/sendSMS.js:4104:18",
            "    at async /var/task/src/handlers/event/sendSMS.js:7736:42",
            "    at async /var/task/src/handlers/event/sendSMS.js:39250:22",
            "    at async /var/task/src/handlers/event/sendSMS.js:1374:26"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: headers[headerName].trim is not a function",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)",
        "    at process.emit (node:events:513:28)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
    ]
}
```

I've double checked and all the items I'm passing to fetch data are correct. My function also has the required IAM role.
To me, the error looks like it's from a node module or the AWS client middy is using. 

To Reproduce
How to reproduce the behaviour:
Sample code:

```ts
import middy from "@middy/core";
import s3 from "@middy/s3";

export const handler = middy((event, context) => {
  try {
    console.log(context);
    console.log(event);
  } catch (error) {
    console.error(error.message);
  }
});

handler.use(
  s3({ fetchData: { config: { Bucket: "sms-templates-test", Key: "templateMessagesSMS.json" } } })
);
```

Error message:
TypeError: headers[headerName].trim is not a function"

Expected behaviour
s3 Middleware should be used without errors.

Environment:

Node.js: 18
Middy: 4.6.1

**Comment by willfarrell** [comment] 2023-09-04 18:03
Internally this middleware does `client.send(new GetObjectCommand({ ...options.fetchData[internalKey],  ChecksumMode: true }))`. Which leads me to think it's:
a) Regression in the AWS SDK, maybe related to `ChecksumMode:true`
b) There are extra environmental variable interfering somehow

I not able to reproduce at this moment, are you able to dig a little deeper?

**Comment by carrickkv2** [comment] 2023-09-04 18:16
> Internally this middleware does `client.send(new GetObjectCommand({ ...options.fetchData[internalKey], ChecksumMode: true }))`. Which leads me to think it's: a) AWS SDK out of date, conflicting versions of AWS SDK clients, or regression in the AWS SDK b) There are extra environmental variable interfering somehow
> 
> I not able to reproduce at this moment, are you able to dig a little deeper?

I was also thinking this is from the AWS SDK. What version are you using?

I'm using this "aws-sdk": "^2.1425.0",

Another thing that comes to mind is that I have a folder in the root called config, which has an index.ts file with the code below

```ts
import { config } from "dotenv";
config();

const env = process.env;
const isDev = env.IS_OFFLINE === "true" || env.NODE_ENV !== "production";

export default () => ({
  aws: {
    region: env.AWS_REGION as string,
    accessKeyId: env.AWS_ACCESS_KEY_ID as string,
    secretAccessKey: env.AWS_SECRET_ACCESS_KEY as string,
    stage: env.AWS_STAGE as string,
    isDev,
  }
  ```

**Comment by willfarrell** [comment] 2023-09-04 18:18
> I'm using this "aws-sdk": "^2.1425.0",
The current version of middy only supports v3

**Comment by carrickkv2** [comment] 2023-09-04 18:40
> > I'm using this "aws-sdk": "^2.1425.0",
> 
> The current version of middy only supports v3

Anyway this can be added to the docs?

Final issue is I don't use the SDK anywhere in my code.
The code above is the only code I have. 
Does having V2 installed automatically invalidate everything?

**Comment by willfarrell** [comment] 2023-09-05 01:21
> Anyway this can be added to the docs?

Install v3 is already in the docs

> Does having V2 installed automatically invalidate everything?

I don't think so.

**Comment by willfarrell** [comment] 2023-09-17 16:10
Found the issue, fix will be in next release.

**Closed** 2023-09-17 16:10 UTC
Labels: bug
