### ISSUE TITLE
middy middleware and separated lambda handler from core logic

### ISSUE THREAD

**Issue by s1mrankaur** [middyjs/middy#607] opened 2021-01-14 20:38 UTC
This is what my middleware looks like:
```

    import middy from '@middy/core'
    import httpJsonBodyParser from '@middy/http-json-body-parser'
    import httpEventNormalizer from '@middy/http-event-normalizer'
    import httpErrorHandler from '@middy/http-error-handler'
    
    
    export default handler => middy(handler)
    .use([
        httpJsonBodyParser(),
        httpEventNormalizer(),
        httpErrorHandler(),
    ]);
```

I am separating core business logic from lambda handler.

In handler.js
```

    'use strict';
    const hello = require("./hello")
    module.exports.hello = async event => { return hello.helloImplementation(); };
    
```

In hello.js

```
    module.exports.helloImplementation =  async => {
    return { statusCode: 200, body: JSON.stringify(         
      { message: 'Go Serverless v1.0! Your function executed successfully!',                      
     }, null, 2       
      ),       };     }
```

Where should the middleware call be added?

**Comment by willfarrell** [comment] 2021-01-14 22:02
Duplicate of #606

**Closed by willfarrell** 2021-01-14 22:02 UTC
