### ISSUE TITLE
Proposal: Way to handle multiple AWS API gateway end points with single handler

### ISSUE THREAD

**Issue by niveditavijayvargiya** [middyjs/middy#719] opened 2021-09-03 13:11 UTC
New Proposal : It will be good if we can some related  AWS API gateway end points with single handler rather writing new handler or new functions for each end points. 
Related end points means:
We have one table of user and want to do all the CRUD operations  using single Middy handler or using single AWS lambda function. 
Purpose: 
1. When you have very large application on serverless architecture it will be difficult to manage that many list of lambda functions.
2. If we consider my above example, its a CRUD operation on same table then all those endpoints shares some common logic which we need to copy in all lambda functions.

**Comment by nponeccop** [comment] 2021-09-03 14:28
> all those endpoints shares some common logic which we need to copy in all lambda functions

- You can always remove copy-paste with enough abstraction in JavaScript code. No middy is necessary
- If you want to do CRUD with a single handler what you need is AWS AppSync, not AWS Lambda
- You can write a custom middleware yourself. Nothing prevents different functions to share parts of middy stack in a reusable way
- Economizing on number of lambdas which do different things (C R U and D are _not_ logically related, only C and U are somewhat related) doesn't look sensible. Moreover you can always make a god lambda (by analogy with the God Object antipattern) and just pass `operationName` parameter and make a `switch` inside.

**Comment by niveditavijayvargiya** [comment] 2021-09-03 14:43
Can we use middle-ware conditionally?

**Comment by willfarrell** [comment] 2021-09-03 14:53
Sounds like a duplicate of https://github.com/middyjs/middy/issues/596 (closing). Something to keep in mind is security, you would only want to group endpoints that share the same IAM permissions.

You can add middleware conditionally by wrapping the setup in a function:
```js

const middleware = (baseHandler, options) => {
  const handler = middy(baseHandler)
    .use(...)

  if (options.db) handler.use(...)

  return {handler}
}

...

module.exports = middleware(handler, options)
```

**Closed by willfarrell** 2021-09-03 14:53 UTC

**Comment by nponeccop** [comment] 2021-09-03 18:13
> Can we use middle-ware conditionally?

Yes. It's normal code, not some magic. I have a system built without middy, which calls middleware manually to parse multipart forms.

**Comment by niveditavijayvargiya** [comment] 2021-09-06 08:59
I want to use Middy validator for json input validation. My request include one parameter as Email and want to se ajv-formats to validate it but didn't find any good documentation that how to use ajv-formats with middy/validator.

**Comment by willfarrell** [comment] 2021-09-07 14:15
@niveditavijayvargiya `ajv-formats` is auto-included. you can just use `"format":"email"`.
