### ISSUE TITLE
SSM middleware fails in AWS because fetching after lambda return

### ISSUE THREAD

**Issue by sorgnardt** [middyjs/middy#1030] opened 2023-03-13 16:07 UTC
**Describe the bug**
On AWS, using lambda middy ssm causes errors on cloudwatch

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TimeoutError: Client network socket disconnected before secure TLS connection was established",
    "reason": {
        "errorType": "TimeoutError",
        "errorMessage": "Client network socket disconnected before secure TLS connection was established",
        "code": "ECONNRESET",
        "path": null,
        "host": "ssm.eu-central-1.amazonaws.com",
        "port": 443,
        "name": "TimeoutError",
        "$metadata": {
            "attempts": 4,
            "totalRetryDelay": 520
        },
        "stack": [
            "Error: Client network socket disconnected before secure TLS connection was established",
            "    at connResetException (node:internal/errors:718:14)",
            "    at TLSSocket.onConnectEnd (node:_tls_wrap:1600:19)",
            "    at TLSSocket.emit (node:events:525:35)",
            "    at TLSSocket.emit (node:domain:489:12)",
            "    at endReadableNT (node:internal/streams/readable:1359:12)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TimeoutError: Client network socket disconnected before secure TLS connection was established",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1188:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.emit (node:domain:489:12)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}

This looks like because the ssm is called , but the lambda ended... This seems to be caused by setInterval , that tries to fetch data, event after the return of the function.

    if (cacheExpiry) {
        const refresh = cacheExpiry > 0 ? setInterval(()=>{
            const value = fetch(request);
            const expiry = Date.now() + cacheExpiry;
            Object.assign(cache[cacheKey], {
                value,
                expiry
            });
        }, cacheExpiry) : undefined;
        cache[cacheKey] = {
            value,
            expiry,
            refresh
        };
    }
    return {
        value,
        expiry
    };
};
**To Reproduce**
- Not possible in unit test. In unit test, we can only see that fetching ssm is done after the lambda returns, but it cause no problem.
- deploy a lambda with SSM + cache invalidation.

**Expected behaviour**

**Environment (please complete the following information):**
 - Node.js: Node 18
 - Middy: 4.2.1
 - AWS SDK  2.1300

**Additional context**
it may be in relation with warmup

**Comment by willfarrell** [comment] 2023-03-13 17:27
Thanks for reporting. Is this a one off occurrence or happens all the time?

In Middy v3 each request would check if the params were expired and re-fetch if needed, blocking the request. Based on an article from AWS about updating expire credential between lambda invocation, I decided to apply the same pattern o Middy. This would reduce the duration of the lambda invocation. We put it through a lot of real world testing on node16.x before releasing to ensure the above didn't happen.

I've just completed some testing using nodejs18.x, but can't seem to reproduce. It's possible the SDK threw an error (very rare, but does happen) and it wasn't handled within Middy on purpose so that you know that there was an error.

**Comment by willfarrell** [comment] 2023-03-25 21:28
I updated a few of my own lambdas with different configurations in production (ca-central-1) to try and reproduce this issue over the last 2 weeks and I'm still unable too. :(

You mentioned containers above, where I use zip files in s3. If that difference is the source of the error, there might be a bug on the AWS side.

Because you have a work around and I'm unable to reproduce, I'm going to close this for now, but will keep an eye out for this in the future.

**Closed by willfarrell** 2023-03-25 21:28 UTC
Labels: bug
