### ISSUE TITLE
Middy no longer bubbles up error messages

### ISSUE THREAD

**Issue by stephenkilbourn** [middyjs/middy#994] opened 2023-01-19 11:09 UTC
**Describe the bug**
In an installation of @middy/core@3.6.2 @middy/ssm@3.6.2, I get clear error messages when my handler fails. After upgrading to @middy/core@4.0.10 @middy/ssm@4.0.10, I am just seeing a `failed to invoke error"

**To Reproduce**
sample code (* note, access is not granted to decode the string): 
```
module.exports.handler = middy(
  metricScope(metrics =>
    async (event, context) => {
      metrics.setNamespace('prod-serverless-workshop')
      metrics.putDimensions({ Service: "lambda-emf-demo" })
      const start = Date.now()
      const req = JSON.parse(event.body)
      const theme = req.theme
      const restaurants = await findRestaurantsByTheme(theme, context.config.defaultResults)
      const response = {
        statusCode: 200,
        body: JSON.stringify(restaurants)
      }
      const end = Date.now()
      console.info(context.secretString)
      metrics.putMetric("latency", end - start, Unit.Milliseconds)
      metrics.setProperty("RequestId", context?.awsRequestId)
      metrics.setProperty("ApiGatewayRequestId", event.requestContext?.requestId)

      return response
  })).use(ssm({
    setToContext: true,
    fetchData: {
      config: `/${serviceName}/${stage}/search-restaurants/config`,
      secretString: `/${serviceName}/${stage}/search-restaurants/secretString`,
    }
  }))
```

**Expected behaviour**
In the older middy version, I can see in my logs:
```
START
2023-01-19 05:01:43.366	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Failed to resolve internal values","cause":[{"errorType":"AccessDeniedException","errorMessage":"The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: d4055d7d-63c6-483a-b07b-2fa7d7fbfbb0; Proxy: null)","code":"AccessDeniedException","message":"The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: d4055d7d-63c6-483a-b07b-2fa7d7fbfbb0; Proxy: null)","time":"2023-01-19T11:01:35.118Z","requestId":"d932a295-afcb-42c2-9265-5b50b145c511","statusCode":400,"retryable":false,"retryDelay":91.94522647240542,"stack":["AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: d4055d7d-63c6-483a-b07b-2fa7d7fbfbb0; Proxy: null)","    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)","    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}],"stack":["Error: Failed to resolve internal values","    at getInternal (/var/task/node_modules/@middy/util/index.cjs:102:23)","    at async ssmMiddlewareBefore (/var/task/node_modules/@middy/ssm/index.cjs:140:26)","    at async runMiddlewares (/var/task/node_modules/@middy/core/index.cjs:126:21)","    at async runRequest (/var/task/node_modules/@middy/core/index.cjs:86:9)"]}
END Duration: 9.84 ms Memory Used: 82 MB
```

In current version, the same error appears as
```
npx sls logs -f search-restaurants --aws-profile workshop
START
2023-01-19 04:44:58.582	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Failed to resolve internal values","stack":["Error: Failed to resolve internal values","    at getInternal (/var/task/node_modules/@middy/util/index.cjs:88:15)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async ssmMiddlewareBefore (/var/task/node_modules/@middy/ssm/index.cjs:135:26)","    at async runMiddlewares (/var/task/node_modules/@middy/core/index.cjs:126:21)","    at async runRequest (/var/task/node_modules/@middy/core/index.cjs:86:9)"]}
END Duration: 89.90 ms (init: 654.03 ms) Memory Used: 100 MB
```

this makes debugging difficult

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 4.0.10
 - AWS SDK 2.1292.0

**Comment by willfarrell** [comment] 2023-01-19 15:32
Thanks for reporting. In v3 we extended the object to include `cause` as a polyfill for the new error cause feature. In v4 we switched to using the proper notation, and dropped the polyfill/hack.

Middy v3
```
const error = new Error('message')
error.cause = ...
throw error
```

Middy v4
```
throw new Error('message', {cause})
```

You'll need to explicitly log the `cause` to have it included. We could update the default handling of error logging in `@middy/error-logger` to include the `cause`. Would this meet your needs?

**Comment by theburningmonk** [comment] 2023-01-19 15:47
@willfarrell thanks for your reply, but the error is happening inside the SSM middleware so there's no place for us to catch the error and log the cause.

I haven't used the `error-logger` middleware before, if you were to make it log the `cause`, then it might help. But I guess we also have to be mindful of the order the middlewares are applied, right?

It still doesn't feel like a very satisfactory solution, to have to solve the problem with another middleware. If an error happens during fetching of SSM parameters, the SSM middleware really oughtta log the necessary information to help debug the problem, as it did before v4.

**Comment by willfarrell** [comment] 2023-01-19 15:59
The best solution would to have Lambda log the `cause` by default when an error is unhandled.

```
$ node -e 'throw new Error("something bad happened", { cause: "cause" })'
[eval]:1
throw new Error("something bad happened", { cause: "cause" })
^

Error: something bad happened
    at [eval]:1:7
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:313:38)
    at node:internal/process/execution:76:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:75:60)
    at node:internal/main/eval_string:28:3 {
  [cause]: 'cause'
}

Node.js v18.8.0
```

As seen above, `cause` is included by default from Node.js. Maybe this is something we need to share with the Node.js runtime team to address properly?

**Comment by willfarrell** [comment] 2023-01-26 07:57
Closing in favour of https://github.com/aws/aws-lambda-base-images/issues/75 because those not using Middy are also affected by this. if you need a workaround in the short term I suggest the middleware above, but won't be helpful if you're `prefetch`ing.

**Closed by willfarrell** 2023-01-26 07:57 UTC
Labels: bug
